[package]
name = "patch-lite"
version = "1.0.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = "1"
serde = "1"
serde_json = "1"
thiserror = "2.0.17"
async-trait = "0.1"

[features]
http-mock = []
